name: Publish to PyPI
on:
  # pull_request:
  #   branches: [main]
  #   types: [closed]
  workflow_dispatch:
    inputs:
      version_no:
        description: 'Release Version:'
        required: true

jobs:
  deploy:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # - name: Update setup.py if manual release
      #   if: github.event_name == 'workflow_dispatch'
      #   run: |
      #     sed -i "s/version='[0-9]\{1,2\}.[0-9]\{1,4\}.[0-9]\{1,4\}',/version='${{github.event.inputs.version_no}}',/g" setup.py
      # - name: Create packages
      #   run: |
      #     python setup.py sdist
      #     python setup.py bdist_wheel
      - name: Create packages
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # repository_url: https://test.pypi.org/legacy/
